/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate the bearer token and return user info */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify username and password
         * @description Authenticate by name + password. Sets an httponly auth cookie and
         *     returns user info on success.
         */
        post: operations["login_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new user account with password and auto-generated token */
        post: operations["signup_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear auth cookie
         * @description Clear the httponly auth cookie.
         */
        post: operations["logout_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check (no auth required)
         * @description Liveness check. Returns the current broker version so the React UI
         *     can detect a broker update and refresh its cached broker list.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brokers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return all active brokers (highest broker version)
         * @description Returns brokers belonging to the highest broker version,
         *     sorted by name for consistent UI ordering.
         */
        get: operations["get_brokers_brokers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brokers/{broker_key}/discover-opt-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run an agent to discover the opt-out URL for a broker
         * @description Spin up a single-tool agent to crawl the broker site for opt-out pages.
         */
        post: operations["discover_opt_out_brokers__broker_key__discover_opt_out_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brokers/{broker_key}/opt-out-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Persist a confirmed opt-out URL for a broker
         * @description Save a user-confirmed opt-out URL to the broker row.
         */
        put: operations["confirm_opt_out_url_brokers__broker_key__opt_out_url_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream audit agent results as SSE events
         * @description Stream audit results as each broker agent completes.
         *
         *     Results with PII detection (found=true/false) are persisted to
         *     broker_field_scans so they're available via GET /fetch.
         *
         *     Events:
         *       - started: list of brokers being scanned + accepted fields
         *       - result: one per broker as its agent finishes
         *       - done: all agents finished
         */
        post: operations["run_agents_audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fetch/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all unexpired scans for the authenticated user
         * @description Returns all unexpired scan executions for the user.
         */
        get: operations["list_scans_fetch_scans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve scan results for the authenticated user
         * @description Returns scan results. If execution_id is provided, returns that
         *     specific scan. Otherwise returns the most recent unexpired scan.
         *
         *     Returns 404 if no matching scan exists.
         */
        get: operations["fetch_scan_fetch_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BrokerOut */
        BrokerOut: {
            /** Version */
            version: number;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Search Url */
            search_url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Opt Out Url */
            opt_out_url?: string | null;
            /** Opt Out Url Source */
            opt_out_url_source?: string | null;
        };
        /** BrokersResponse */
        BrokersResponse: {
            /** Version */
            version: number;
            /** Brokers */
            brokers: components["schemas"]["BrokerOut"][];
        };
        /** ConfirmOptOutUrl */
        ConfirmOptOutUrl: {
            /** Opt Out Url */
            opt_out_url: string;
        };
        /** FetchResponse */
        FetchResponse: {
            /**
             * Execution Id
             * Format: uuid
             */
            execution_id: string;
            /** Name */
            name: string | null;
            /** Broker Version */
            broker_version: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Results */
            results: components["schemas"]["FetchResult"][];
            summary: components["schemas"]["FetchSummary"];
        };
        /**
         * FetchResult
         * @description A single stored result returned from /fetch.
         */
        FetchResult: {
            /**
             * Broker Id
             * Format: uuid
             */
            broker_id: string;
            /** Broker Key */
            broker_key: string;
            /** Broker Name */
            broker_name: string;
            /** Search Url */
            search_url: string;
            /** Field Type */
            field_type: string;
            state: components["schemas"]["ScanState"];
            /** Found */
            found: boolean;
            /** Message */
            message?: string | null;
            /** Opt Out Url */
            opt_out_url?: string | null;
        };
        /** FetchSummary */
        FetchSummary: {
            /** Total Brokers Scanned */
            total_brokers_scanned: number;
            /** Total Results */
            total_results: number;
            /** Found Count */
            found_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Broker Version */
            broker_version: number;
            /** Agent Timeout Seconds */
            agent_timeout_seconds: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
        };
        /** MeResponse */
        MeResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string | null;
            /**
             * Token Id
             * Format: uuid
             */
            token_id: string;
            /** Token Name */
            token_name: string | null;
        };
        /** RunAuditAgentsRequest */
        RunAuditAgentsRequest: {
            /** Broker Keys */
            broker_keys: string[];
            /** Save */
            save: boolean;
            /** Scan Name */
            scan_name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Name */
            name?: string | null;
            /** Address */
            address?: string | null;
        };
        /** ScanListItem */
        ScanListItem: {
            /**
             * Execution Id
             * Format: uuid
             */
            execution_id: string;
            /** Name */
            name: string | null;
            state: components["schemas"]["ScanState"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Broker Count */
            broker_count: number;
            /** Found Count */
            found_count: number;
            /** Incomplete Count */
            incomplete_count: number;
        };
        /** ScanListResponse */
        ScanListResponse: {
            /** Scans */
            scans: components["schemas"]["ScanListItem"][];
        };
        /**
         * ScanState
         * @enum {string}
         */
        ScanState: "RUNNING" | "SUCCESS" | "CANCELLED" | "FAILED";
        /** SignupRequest */
        SignupRequest: {
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /** SignupResponse */
        SignupResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    login_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_brokers_brokers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrokersResponse"];
                };
            };
        };
    };
    discover_opt_out_brokers__broker_key__discover_opt_out_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                broker_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_opt_out_url_brokers__broker_key__opt_out_url_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                broker_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmOptOutUrl"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_agents_audit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunAuditAgentsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scans_fetch_scans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanListResponse"];
                };
            };
        };
    };
    fetch_scan_fetch_get: {
        parameters: {
            query?: {
                execution_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
